version: '3.8'

services:
  websocket:
    build: .
    container_name: websocket-service
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8090
      - APP_URL=${APP_URL:-http://192.168.2.75}
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
